---
abstract: 'check that your version of Perl is old enough to consent'
author:
  - 'Michael G Schwern <mschwern@cpan.org>'
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Acme::Perl::Consensual
name: Acme-Perl-Consensual
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Acme-Perl-Consensual
  homepage: https://metacpan.org/release/Acme-Perl-Consensual
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-acme-perl-consensual
version: 0.000_01
